"""Interfaces between the core and the outside world (storage, browser, LLM)."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from .models import (
    AccountState,
    Action,
    LeadRecord,
    LeadSequence,
    LeadStage,
    ReviewItem,
    Task,
    TaskResult,
    TaskStatus,
)


class TaskQueue(Protocol):
    async def enqueue(self, task: Task) -> None: ...

    async def claim_next(self, account: str, now: datetime) -> Task | None: ...

    async def claim(self, task_id: str, now: datetime) -> Task | None: ...

    async def finish(self, task_id: str, result: TaskResult | None, status: TaskStatus) -> None: ...

    async def expire_overdue(self, now: datetime) -> int: ...

    async def requeue_stale_running(self, now: datetime, older_than_s: int) -> int: ...

    async def open_task_for(self, lead_id: str, step_id: str) -> Task | None: ...

    async def count_open(self, account: str, action: Action) -> int: ...

    async def get(self, task_id: str) -> Task | None: ...

    async def update(self, task: Task) -> None: ...

    async def list_by_status(self, status: TaskStatus, limit: int = 50) -> list[Task]: ...

    async def recent(self, limit: int = 10) -> list[Task]: ...

    async def body_sent_recently(self, account: str, body_hash: str, since: datetime) -> bool: ...

    async def depth(self, account: str) -> dict[str, int]: ...

    async def for_lead(self, lead_id: str) -> list[Task]: ...

    async def cancel_open_for_leads(
        self, lead_ids: list[str], reason: str = "cancelled"
    ) -> int: ...


class LeadStore(Protocol):
    async def get(self, lead_id: str) -> LeadRecord | None: ...

    async def find(self, key: str) -> LeadRecord | None: ...

    async def upsert_many(self, leads: list[LeadRecord]) -> tuple[int, int]: ...

    async def update(self, lead: LeadRecord) -> None: ...

    async def get_sequence(self, lead_id: str) -> LeadSequence | None: ...

    async def save_sequence(self, seq: LeadSequence) -> None: ...

    async def due_sequences(
        self, now: datetime, campaign: str | None = None
    ) -> list[tuple[LeadRecord, LeadSequence]]: ...

    async def by_stage(self, stage: LeadStage, campaign: str | None = None) -> list[LeadRecord]: ...

    async def all(self, campaign: str | None = None) -> list[LeadRecord]: ...

    async def stage_counts(self, campaign: str | None = None) -> dict[str, int]: ...

    async def acceptance_sample(
        self, start: datetime, end: datetime, campaign: str | None = None
    ) -> tuple[int, int]: ...


class ActionLog(Protocol):
    async def record(
        self,
        account: str,
        action: Action,
        lead_id: str | None,
        ok: bool,
        result_status: str | None,
        at: datetime,
    ) -> None: ...

    async def count(self, account: str, action: Action, since: datetime) -> int: ...

    async def touches(self, lead_id: str, since: datetime) -> int: ...

    async def recent(
        self, account: str, action: Action | None, limit: int
    ) -> list[dict[str, Any]]: ...


class AccountStore(Protocol):
    async def get(self, name: str) -> AccountState: ...

    async def save(self, state: AccountState) -> None: ...


class ReviewQueue(Protocol):
    async def submit(
        self, task_id: str, kind: str, context: dict[str, Any], draft: str
    ) -> None: ...

    async def pending(self) -> list[ReviewItem]: ...

    async def get(self, task_id: str) -> ReviewItem | None: ...

    async def decide(self, task_id: str, approved_text: str | None, at: datetime) -> None: ...


class TextLLM(Protocol):
    async def complete(self, prompt: str, *, temperature: float = 0.7) -> str: ...


class TaskExecutor(Protocol):
    async def execute(self, task: Task, browser: Any) -> TaskResult: ...


class BrowserProvider(Protocol):
    """Subset of BrowserPool the runner depends on."""

    async def get_browser(self, account: str) -> Any: ...

    def mark_browser_dead(self) -> None: ...

    def increment_task_count(self) -> None: ...

    async def cleanup_pages(self) -> None: ...

    async def maybe_close_idle(self, idle_seconds: float) -> None: ...

    async def shutdown(self) -> None: ...

    async def verify_session(self, account: str) -> bool | None: ...

    @property
    def has_active_browser(self) -> bool: ...
